### ISSUE TITLE
Addon doesn't connect remote boblightd on Android

### ISSUE THREAD

**Issue by newkind** [bobo1on1/script.xbmc.boblight#32]
Hi,

I'm reporting the issue with the addon and Android environment (4.4.2 in my case). On the latest Kodi beta 5 and latest addon version from the Kodi's repository the addon doesn't connect to the remote boblightd. Everytime you enable/disable the addon the message pops-up that it requires to the binaries and to check the Readme.

I just wanted to mention that other Android applications that allow boblight control ie. BobDroid, are working just fine, and connect successfully.

If there's a way to debug the connection, I'll provide all the logs that I can to help!

Thank you!

**Comment by webnar** [comment]
How can i install boblight on android? I have a rooted ARM device. But have no clue how to configure or install it.

**Comment by nikitociko** [comment]
Hi! boblight.conf  where it should be in android device? Thank you

**Comment by Memphiz** [comment]
It has to be where your boblightd server is running (which can not be an android device). Only the addon can be run on android (which is only the client).

**Comment by nikitociko** [comment]
And where can I start boblightd server? Can I do it on openwrt router? How wil kodi communicate with router?

**Comment by Memphiz** [comment]
Please continue in the forum - its all described in the first post of the boblight addon already...

**Comment by Tommixoft** [comment]
Hi what's the main reason it doesn't run on android?
