### ISSUE TITLE
Static color on custom android firmware

### ISSUE THREAD

**Issue by newkind** [bobo1on1/script.xbmc.boblight#35]
Hey!

Recently I've been testing some custom Android firmwares and I found an issue that maybe you'll help me to figure out. When playing any video content boblight acts like it would be set up to static light only - all leds are glowing in orange and don't change. Can this be a permission issue ? I had to change the permissions to allow Kodi access the libboblight.so in /data/data/org.xbmc/kodi/files/ so maybe there's another directory that needs to get it's permissions changed too (buffer directory) ?

Here's my log : http://pastebin.com/UBu9iUu2

**Comment by newkind** [comment]
@Memphiz looks like this is caused by the RKlibstagefright hardware acceleration codec - if I disable it in the Kodi settings and leave the 2 others untouched (libstagefright and mediacodec) it works just fine. This RKlibstagefright is most likely a RockChip hardware acceleration codec - the question is that is it broken or needs to be enabled/added to the Boblight addon ?

Thanks!
Jakub

**Comment by Memphiz** [comment]
RKlibstagefright is nothing from team kodi. Its not part of our code. Whoever implemented RKlibstagefright needs to implement the RenderCapture class for making boblight work. Nothing i can do about.

**Comment by newkind** [comment]
Oh allright, thank you for clarification. So I guess we can mark this as invalid :)
